# Generated by Django 4.2.15 on 2024-08-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('job_classification', models.CharField(max_length=100)),
                ('date_joined', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
