# Generated by Django 4.2.15 on 2024-08-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bank',
            name='customer_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='job_classification',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bank',
            name='region',
            field=models.CharField(max_length=255),
        ),
    ]
