# Generated by Django 4.2.15 on 2024-08-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('words', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('cheque_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
