# Generated by Django 4.2.15 on 2024-08-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='cheque_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='client',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='words',
            field=models.TextField(),
        ),
    ]
