# Generated by Django 4.2.9 on 2024-08-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_image', models.ImageField(upload_to='cheque_images/')),
                ('cheque_id', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('amount_digits', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('corrected_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
            ],
        ),
    ]
