# Generated by Django 4.2.15 on 2024-08-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_id', models.CharField(max_length=255, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('amount_digits', models.CharField(max_length=255)),
                ('amount_words', models.TextField()),
                ('date', models.DateField()),
                ('corrected_amount', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Cheque',
        ),
    ]
