# Generated by Django 4.2.15 on 2024-08-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0002_chequedata_delete_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedata',
            name='amount_words',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chequedata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chequedata',
            name='is_correct',
            field=models.BooleanField(),
        ),
    ]
