# Generated by Django 4.2.15 on 2024-08-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0004_chequedata_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequedata',
            name='image_path',
        ),
        migrations.AddField(
            model_name='chequedata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
