# Generated by Django 4.2.15 on 2024-08-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0005_remove_chequedata_image_path_chequedata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedata',
            name='amount_words',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chequedata',
            name='cheque_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='chequedata',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
